export const splash_Icon = require('../Assets/Images/splashIcon.png');
export const manastha_Image = require('../Assets/Images/manasthaImage.png');
export const bookConsult1 = require('../Assets/Images/bookConsult.png');
export const bookConsult = require('../Assets/Images/grp2.png');
export const coOpUser = require('../Assets/Images/grp3.png');
export const exploring = require('../Assets/Images/grp1.png');
export const Intro = require('../Assets/Images/Intro.png');
export const firstTimeUser = require('../Assets/Images/firstTimeUser.png');
export const Slider_1 = require('../Assets/Images/Slider_1.png');
export const mail = require('../Assets/Images/mail.png');
export const password = require('../Assets/Images/password.png');
export const eye_Open = require('../Assets/Images/EyeOpen.png');
export const user = require('../Assets/Images/user.png');
export const phone = require('../Assets/Images/phone.png');
export const tick =require('../Assets/Images/tick.png')
export const close =require('../Assets/Images/close.png')
export const unCheck =require('../Assets/Images/unChecked.png')
export const company =require('../Assets/Images/company.png')
export const closeeEye =require('../Assets/Images/closeEye.png')
export const login =require('../Assets/Images/login.png')
export const profile =require('../Assets/Images/profile.png')
export const session =require('../Assets/Images/session.png')
export const home =require('../Assets/Images/home.png')
export const chat =require('../Assets/Images/chat.png')
export const tool =require('../Assets/Images/tool.png')
export const toolDrawer =require('../Assets/Images/ToolsDrawer.png')
export const startTheripist =require('../Assets/Images/startTheripist.png')
export const therapist =require('../Assets/Images/therapist.png')
export const editProfile =require('../Assets/Images/EditProfile.png')
export const caseHistory =require('../Assets/Images/caseHistory.png')
export const psyProgram =require('../Assets/Images/psyProgram.png')
export const psyTest =require('../Assets/Images/psyTest.png')
export const settings =require('../Assets/Images/Setting.png')
export const offlineConsult =require('../Assets/Images/offlineConsultent.png')
export const arrow =require('../Assets/Images/arrow.png')
export const prime =require('../Assets/Images/prime.png')
export const notification =require('../Assets/Images/notification.png')
export const services_homescreen =require('../Assets/Images/services-bg-homescreen.png')
export const banner =require('../Assets/Images/banner.png')
export const star =require('../Assets/Images/star.png')
export const timer =require('../Assets/Images/timer.png')
export const banner2 =require('../Assets/Images/banner2.png')
export const downArrow =require('../Assets/Images/downArrow.png')
export const camera =require('../Assets/Images/camera.png')
export const country =require('../Assets/Images/country.png')
export const primeStar =require('../Assets/Images/primeStar.png')
export const correct =require('../Assets/Images/correct.png')
export const minus =require('../Assets/Images/minus.png')
export const plus =require('../Assets/Images/plus.png')
export const brain =require('../Assets/Images/brain.png')
export const mobile =require('../Assets/Images/mobile.png')
export const support =require('../Assets/Images/support.png')
export const address =require('../Assets/Images/address.png')
export const pinCode =require('../Assets/Images/pinCode.png')
export const minute =require('../Assets/Images/minute.png')
export const videoCall =require('../Assets/Images/videoCall.png')
export const download =require('../Assets/Images/download.png')
export const regUser =require('../Assets/Images/registerUser.png')
export const description =require('../Assets/Images/desc.png')
export const genderIcon =require('../Assets/Images/gender.png')
export const userImg =require('../Assets/Images/userImg.png')
export const bookPshy =require('../Assets/Images/bookPshy.png')
export const confused =require('../Assets/Images/confused.png')
export const userbookPhsliration =require('../Assets/Images/Psychiatrist.png')
export const line =require('../Assets/Images/line.png')
export const uploadIcon =require('../Assets/Images/uploadImage.png')
export const calender =require('../Assets/Images/calender.png')
export const pdf =require('../Assets/Images/pdf.png')
export const provider =require('../Assets/Images/provider.png')
export const document =require('../Assets/Images/document.png')
export const editIcon =require('../Assets/Images/editIcon.png')
export const chats =require('../Assets/Images/chats.png')
export const video =require('../Assets/Images/video.png')
export const audio =require('../Assets/Images/audio.png')
export const therapistEmpty =require('../Assets/Images/therapistEmpty.png')
export const play =require('../Assets/Images/play.png')
export const mic =require('../Assets/Images/mic1.png')
export const share =require('../Assets/Images/share.png')
export const floatingButton =require('../Assets/Images/floatingButton.png')
export const journaling =require('../Assets/Images/journaling.png')
export const quoteFloating =require('../Assets/Images/quotefloating.png')
export const deleteIcon = require('../Assets/Images/delete.png')
export const quote = require('../Assets/Images/quote.png')
export const dropDown = require('../Assets/Images/dropDown.png')
export const dropUp = require('../Assets/Images/dropUp.png')
export const joinUs1 = require('../Assets/Images/joinUs1.png')
export const joinUs2 = require('../Assets/Images/joinUs2.png')
export const floatingVideo = require('../Assets/Images/floatingVideo.png')
export const text = require('../Assets/Images/text.png')
export const IntroArrow = require('../Assets/Images/introArrow.png')
export const rightArrow = require('../Assets/Images/arrowRight.png')
export const locationIcon = require('../Assets/Images/location.png')
export const read = require('../Assets/Images/read.png')
export const readMe = require('../Assets/Images/readMe.png')
export const bookConsultent=require('../Assets/Images/bookConsultent.png')
export const sessionCompletd=require('../Assets/Images/sessionCompleted.png')
export const warning=require('../Assets/Images/warning.png')
export const send=require('../Assets/Images/send.png')
export const attachment=require('../Assets/Images/attachment.png')
export const radio_checked=require('../Assets/Images/radio_checked.jpeg')
export const radio_Unchecked=require('../Assets/Images/radio_outlined.png')
export const videoPlayer=require('../Assets/Images/videoPlayer.png')
export const checkedImage=require('../Assets/Images/checkedImage.png')
export const remaining=require('../Assets/Images/remaining.png')
export const essential = require('../Assets/Images/essential.png');
export const videoIcon = require('../Assets/Images/videoIcon.png');
export const audioIcon = require('../Assets/Images/audioIcon.png');
export const placeHolder = require('../Assets/Images/Suggested.png');
export const verified = require('../Assets/Images/verified.png');
export const noData = require('../Assets/Images/noData.png');
export const backIcon = require('../Assets/Images/backIcon.png');
export const micOpen = require('../Assets/Images/micOpen.png');
export const openChat = require('../Assets/Images/openChat.png');
export const closeVideo = require('../Assets/Images/closeVideo.png');
export const sessionVideo = require('../Assets/Images/videoSession.png');
export const sessionAudio = require('../Assets/Images/voiceSession.png');
export const sessionChat = require('../Assets/Images/chatSession.png');
export const audioHolder = require('../Assets/Images/audioHolder.png');
export const refresh = require('../Assets/Images/refresh.png');
export const cameraBack = require('../Assets/Images/cameraFlip.png');
export const flash = require('../Assets/Images/flash.jpeg');
export const end = require('../Assets/Images/end.png');
export const mute = require('../Assets/Images/unmute.png');
export const chatVideo = require('../Assets/Images/chatVideo.png');
export const muteVideo = require('../Assets/Images/muteVideo.png');
export const quoteIcon = require('../Assets/Images/quoteIcon.png');
export const cross = require('../Assets/Images/cross.png');
export const record = require('../Assets/Images/Record.png');
export const done = require('../Assets/Images/Done.png');
export const doubleTick = require('../Assets/Images/doubleTick.png');
export const imgIcon=require('../Assets/Images/imgIcon.png');
export const videoPause=require('../Assets/Images/videoPause.png');
export const price=require('../Assets/Images/price.png');
export const watsup=require('../Assets/Images/watsup.png');
export const psycho=require('../Assets/Images/psychological.png');
export const search=require('../Assets/Images/search.png');
export const videoStart=require('../Assets/Images/videoStart.png');
export const radioChecked=require('../Assets/Images/radioChecked.png');
export const radioUnchecked=require('../Assets/Images/radioUnchecked.png');
export const playIcon=require('../Assets/Images/playButton.png');
export const crossIcon=require('../Assets/Images/crossIcon.png');
export const biometric=require('../Assets/Images/biometric.png');
